namespace OpenClaw.Launcher.Gateway;

/// <summary>
/// Generates the single launcher file both persistence lanes invoke.
/// </summary>
internal static class GatewayLauncherScript
{
    /// <summary>
    /// Identifies a file this installation generated, so a file that happens to
    /// share the name is reported rather than silently overwritten.
    /// </summary>
    public const string Marker = "@rem openclaw-gateway-launcher v1";

    public static string Create(string workingDirectory, string aliasCommand)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workingDirectory);
        ArgumentException.ThrowIfNullOrWhiteSpace(aliasCommand);

        // At logon a task's working directory is the system directory. The
        // gateway is given an explicit, controlled one instead, so it never
        // writes relative paths into a system location.
        return string.Join(
            "\r\n",
            "@echo off",
            Marker,
            "@rem Generated by OpenClaw. Edits are overwritten on the next install.",
            "setlocal",
            $"cd /d \"{workingDirectory}\" || exit /b 1",
            $"\"{aliasCommand}\" gateway-service start",
            "exit /b %ERRORLEVEL%",
            string.Empty);
    }

    /// <summary>
    /// The Startup-folder fallback calls the same launcher rather than
    /// repeating its contents, so the two lanes cannot drift apart.
    /// </summary>
    public static string CreateFallback(string launcherPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(launcherPath);

        return string.Join(
            "\r\n",
            "@echo off",
            Marker,
            "@rem Generated by OpenClaw. Edits are overwritten on the next install.",
            $"call \"{launcherPath}\"",
            string.Empty);
    }

    public static bool LooksGenerated(string content)
    {
        ArgumentNullException.ThrowIfNull(content);
        return content.Contains(Marker, StringComparison.Ordinal);
    }
}
