namespace OpenClaw.Launcher.Gateway;

/// <summary>
/// Generates the launcher files both persistence lanes invoke.
/// </summary>
internal static class GatewayLauncherScript
{
    /// <summary>
    /// Identifies a file this installation generated, so a file that happens to
    /// share the name is reported rather than silently overwritten.
    /// </summary>
    public const string Marker = "@rem openclaw-gateway-launcher v1";

    private const string PowerShellMarker = "# openclaw-gateway-launcher v1";

    public const string ControlApplicationId = "Control";

    public const string ControlArguments = "gateway-service start";

    public static string Create(string workingDirectory, string activationScriptPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workingDirectory);
        ArgumentException.ThrowIfNullOrWhiteSpace(activationScriptPath);

        // At logon a task's working directory is the system directory. The
        // gateway is given an explicit, controlled one instead, so it never
        // writes relative paths into a system location.
        return string.Join(
            "\r\n",
            "@echo off",
            Marker,
            "@rem Generated by OpenClaw. Edits are overwritten on the next install.",
            "chcp 65001 >nul",
            "setlocal",
            $"cd /d \"{workingDirectory}\" || exit /b 1",
            $"\"%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -NoProfile -ExecutionPolicy Bypass -File \"{activationScriptPath}\"",
            "exit /b %ERRORLEVEL%",
            string.Empty);
    }

    public static string CreateActivationScript(string packageFamilyName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(packageFamilyName);

        string applicationUserModelId =
            $"{packageFamilyName}!{ControlApplicationId}";
        return string.Join(
            "\r\n",
            PowerShellMarker,
            "$ErrorActionPreference = 'Stop'",
            $"$packageFamilyName = '{QuotePowerShell(packageFamilyName)}'",
            $"$applicationId = '{ControlApplicationId}'",
            $"$arguments = '{ControlArguments}'",
            $"$applicationUserModelId = '{QuotePowerShell(applicationUserModelId)}'",
            "$package = Get-AppxPackage -Name 'OpenClaw.Gateway' | " +
            "Where-Object { $_.PackageFamilyName -eq $packageFamilyName } | " +
            "Select-Object -First 1",
            "if ($null -eq $package) { throw \"Package '$packageFamilyName' is not registered for the current user.\" }",
            "if ($package.Status -inotmatch '^(Ok|Ready)$') { throw \"Package '$packageFamilyName' is not ready (status $($package.Status)).\" }",
            "$manifestPath = Join-Path $package.InstallLocation 'AppxManifest.xml'",
            "if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) { throw \"Package '$packageFamilyName' has no AppxManifest.xml at $manifestPath.\" }",
            "[xml]$manifest = Get-Content -LiteralPath $manifestPath -Raw",
            "$application = @($manifest.Package.Applications.Application | Where-Object { $_.Id -eq $applicationId }) | Select-Object -First 1",
            "if ($null -eq $application) { throw \"Package '$packageFamilyName' does not declare application '$applicationId'.\" }",
            "if ([string]$application.Executable -ne 'openclaw.exe') { throw \"Package '$packageFamilyName' application '$applicationId' does not target openclaw.exe.\" }",
            "$source = @'",
            "using System;",
            "using System.ComponentModel;",
            "using System.Runtime.InteropServices;",
            "namespace OpenClaw.PackageActivation",
            "{",
            "    [ComImport]",
            "    [Guid(\"2e941141-7f97-4756-ba1d-9decde894a3d\")]",
            "    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]",
            "    public interface IApplicationActivationManager",
            "    {",
            "        [PreserveSig]",
            "        int ActivateApplication(",
            "            [MarshalAs(UnmanagedType.LPWStr)] string appUserModelId,",
            "            [MarshalAs(UnmanagedType.LPWStr)] string arguments,",
            "            uint options,",
            "            out uint processId);",
            "    }",
            "",
            "    [ComImport]",
            "    [Guid(\"45ba127d-10a8-46ea-8ab7-56ea9078943c\")]",
            "    public class ApplicationActivationManager",
            "    {",
            "    }",
            "",
            "    public static class ApplicationActivator",
            "    {",
            "        private const uint Synchronize = 0x00100000;",
            "        private const uint QueryLimitedInformation = 0x1000;",
            "        private const uint Infinite = 0xffffffff;",
            "        private const uint WaitObject0 = 0;",
            "",
            "        [DllImport(\"kernel32.dll\", SetLastError = true)]",
            "        private static extern IntPtr OpenProcess(uint desiredAccess, bool inheritHandle, uint processId);",
            "",
            "        [DllImport(\"kernel32.dll\", SetLastError = true)]",
            "        private static extern uint WaitForSingleObject(IntPtr handle, uint milliseconds);",
            "",
            "        [DllImport(\"kernel32.dll\", SetLastError = true)]",
            "        [return: MarshalAs(UnmanagedType.Bool)]",
            "        private static extern bool GetExitCodeProcess(IntPtr process, out uint exitCode);",
            "",
            "        [DllImport(\"kernel32.dll\")]",
            "        [return: MarshalAs(UnmanagedType.Bool)]",
            "        private static extern bool CloseHandle(IntPtr handle);",
            "",
            "        public static int ActivateAndWait(string appUserModelId, string arguments)",
            "        {",
            "            var manager =",
            "                (IApplicationActivationManager)new ApplicationActivationManager();",
            "            uint processId;",
            "            int result = manager.ActivateApplication(",
            "                appUserModelId,",
            "                arguments,",
            "                0,",
            "                out processId);",
            "            if (result != 0)",
            "            {",
            "                Marshal.ThrowExceptionForHR(result);",
            "            }",
            "",
            "            IntPtr process = OpenProcess(",
            "                Synchronize | QueryLimitedInformation,",
            "                false,",
            "                processId);",
            "            if (process == IntPtr.Zero)",
            "            {",
            "                throw new Win32Exception(Marshal.GetLastWin32Error());",
            "            }",
            "",
            "            try",
            "            {",
            "                uint exitCode;",
            "                if (WaitForSingleObject(process, Infinite) != WaitObject0 ||",
            "                    !GetExitCodeProcess(process, out exitCode))",
            "                {",
            "                    throw new Win32Exception(Marshal.GetLastWin32Error());",
            "                }",
            "",
            "                return checked((int)exitCode);",
            "            }",
            "            finally",
            "            {",
            "                CloseHandle(process);",
            "            }",
            "        }",
            "    }",
            "}",
            "'@",
            "Add-Type -TypeDefinition $source -Language CSharp",
            "$exitCode = [OpenClaw.PackageActivation.ApplicationActivator]::ActivateAndWait($applicationUserModelId, $arguments)",
            "exit $exitCode",
            string.Empty);
    }

    /// <summary>
    /// The Startup-folder fallback calls the same launcher rather than
    /// repeating its contents, so the two lanes cannot drift apart.
    /// </summary>
    public static string CreateFallback(string launcherPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(launcherPath);

        return string.Join(
            "\r\n",
            "@echo off",
            Marker,
            "@rem Generated by OpenClaw. Edits are overwritten on the next install.",
            "chcp 65001 >nul",
            $"call \"{launcherPath}\"",
            "exit /b %ERRORLEVEL%",
            string.Empty);
    }

    public static bool LooksGenerated(string content)
    {
        ArgumentNullException.ThrowIfNull(content);
        return content.Contains(Marker, StringComparison.Ordinal) ||
               content.Contains(PowerShellMarker, StringComparison.Ordinal);
    }

    private static string QuotePowerShell(string value) =>
        value.Replace("'", "''", StringComparison.Ordinal);
}
